### ISSUE TITLE
Zla navratova hodnota funkcie getPDF()

### ISSUE THREAD

**Issue by s1t2e3** [superfaktura/apiclient#10]
V pripade chyby(neexistujuca faktura, zly token) funkcia getPDF() vrati string namiesto objektu stdClass. Je to takto spravne alebo je to chyba? Fukcia nema ziadny komentar a tak neviem co je spravne.

**Comment by superfaktura** [comment]
Je to takto spravne. Pracujeme vsak na uprave API klienta.

Dovtedy moze pomoct vseobecna dokumentacia na adrese: https://github.com/superfaktura/docs/blob/master/invoice.md#get-invoice-pdf

**Comment by s1t2e3** [comment]
Vsimol som si ze ste vydali novu verziu 1.22 ale nie je mozne ju nainstalovat cez composer https://packagist.org/packages/superfaktura/apiclient.

**Comment by superfaktura** [comment]
Uz je mozne ju nainstalovat, ale odporucame poslednu 1.22.2 :)

**Comment by s1t2e3** [comment]
Info: Navratova hodnota funkcie `getPdf()` je null alebo objekt `Requests_Response`. Je to takto spravne? V docbloku je `@return mixed|stdClass`

**Comment by superfaktura** [comment]
@s1t2e3 Docblocky upravene pre viacere metody. Dakujeme :)

**Comment by s1t2e3** [comment]
Upravene su ale znovu zle. Navratova hodnota funkcie `public function get($url, $json_decode = true)` je null alebo na zaklade druheho parametra `json_decode` bud `stdClass` alebo object `Requests_Response`. Takze vo fukcii `getPdf` ste to opravili spravne ale napriklad funkcia `invoice($id)` vrati `stdClass` co podla dockblocku nesedi.

**Comment by superfaktura** [comment]
Navratova hodnota je spravna. `mixed` je typ navratovej hodnoty z `json_decode` (https://www.php.net/manual/en/function.json-decode.php) a urcuje viacero typov (https://www.php.net/manual/en/language.pseudo-types.php#language.types.mixed).

Kazdopadne pridal som explicitne aj `stdClass`.
