### ISSUE TITLE
PHP 7.4 kompatibilita

### ISSUE THREAD

**Issue by slano** [superfaktura/apiclient#12]
https://github.com/superfaktura/apiclient/blob/ad50fb7f8633d6d90b67113ec78c7a81d178a3df/SFAPIclient/Requests/Transport/fsockopen.php#L105

PHP 7.4 oznacilo taketo poradie parametrov pre implode() za deprecated. Je potrebne zamenit za ```implode("\r\n", $headers)```. Niektore frameworky (napriklad Laravel) totiz mozu PHP warning odchytit a vygenerovat tak Exception

apiClient->getLastError()
```
array:3 [
  "status" => 500
  "message" => {#948
    +"error": 99
    +"error_message": "implode(): Passing glue string after array is deprecated. Swap the parameters"
  }
  "checksum" => "ffc1b7861995c4156503d4a358ffc3cd"
]

```

**Comment by superfaktura** [comment]
Ďakujeme za upozornenie, v najnovšej verzii API klienta to je už zmenené.
