### ISSUE TITLE
Invalid post data po uprave fsockopen.php

### ISSUE THREAD

**Issue by slano** [superfaktura/apiclient#13]
https://github.com/superfaktura/apiclient/blob/b4b065f5f9f55cf4e5054f07e479f3fa822980fc/SFAPIclient/Requests/Transport/fsockopen.php#L107

prazdny riadok na konci sposobuje "Invalid post data" pri komunikacii pomocou api klienta:
```
$apiClient->markAsSent($order->external_id, $order->email);
{#3195
     +"error": 1,
     +"error_message": "Invalid post data",
}
```

**Comment by superfaktura** [comment]
ďakujeme, opravené.
