### ISSUE TITLE
PDF do emailu pomocou vlastnej mail funkcie

### ISSUE THREAD

**Issue by matuskm** [superfaktura/apiclient#20]
Dobrz den,

chcem sa spytat ako dostanem pdf subor tak aby som ho mohol pridat do prilohy ale pomocou vlastnej funkcie mail. 

Potrebujem si najprv ulozit niekam do temp PDF cez getPDF() a potom to odoslat??

**Comment by matuskm** [comment]
Zistil som to, ze ak sa pokusam volat `getPDF()` s pouzitim `useSandBox()` tak mi `getPDF()` nefunguje. Je mozne, ze je tam nejaky bug? Alebo to vobec nema fungovat?

**Comment by superfaktura** [comment]
Dobrý deň,
posielam Vám ukážku kódu ako dostane pdf k Vám na disk. 

`$api = new SFAPIclient(SFAPI_EMAIL, SFAPI_KEY, SFAPI_APPTITLE, SFAPI_MODULE, COMPANY_ID);`
`$pdf = $api->getPDF(INVOICE_ID, TOKEN);`
`file_put_contents('superfaktura.pdf', $pdf->body);`

Čo sa týka funkcie `getPDF()` s použítím `useSandBox()` vedeli by ste nám poslať (info@superfaktura.sk) ukážku Vašej implementácie a zároveň aj ID dokladu, na ktorý sa dopytujete a nefunguje Vám to. Najlepšie bude ak nám pošlete aj chybovú hlášku, ktorú dostanete po zavolaní `$api->getLastError();`

**Comment by matuskm** [comment]
dakujem uz nam to funguje. Problem som mal v tom, ze som nevytahoval z "$pdf" to "body ".
