### ISSUE TITLE
getPDF is not working as intended

### ISSUE THREAD

**Issue by jsaak** [superfaktura/apiclient#21]
in function `  public function get($url, $json_decode = true)`
at `SFAPIclient.php:1124` 

```
            return !empty($json_decode) ? json_decode($response->body) : $response;
```

should be:
```
            return !empty($json_decode) ? json_decode($response->body) : $response->body;
```

**Comment by superfaktura** [comment]
Returning $response->body directly would strip other relevant information from the response. You are right the documentation and return type could be better and we will improve it.
