### ISSUE TITLE
This repository is not well maintained, so you should NOT use it. Ever. Use the REST documentation, and call curl yourself instead.

### ISSUE THREAD

**Issue by jsaak** [superfaktura/apiclient#22]
For those who try to integrate superfaktura.sk
My advice is this:
This repository is not well maintained, so you should NOT use it. Ever. Use the REST documentation, and call curl yourself instead.

**Comment by superfaktura** [comment]
We are aware that our API client is obsolete.
We have planned a major update with breaking changes which will be released as version 2, but unfortunately it has no release date yet.

Our API client is recommended for ready-to-use solution for easy and simple integration with SuperFaktúra. For customized solutions that have more complex requirements we recommend custom implementation based on our general REST API documentation.
Just as you say, for developers who want to have more control of their code, or prefer their own handling, we recommend [general documentation](https://github.com/superfaktura/docs).
As README says:
> Aby ste sa nemuseli trápiť s priamymi volaniami API funkcií a spôsobom prenosu dát, pripravili sme pre Vás jednoduchého API klienta, vďaka ktorému môžete Vaše faktúry vystavovať nadiaľku s minimálnym úsilím.
> Ak si však chcete vytvoriť vlastného API klienta, máme aj všeobecnú dokumentáciu.
