### ISSUE TITLE
Chyby po upgrade na PHP 8.1(.6)

### ISSUE THREAD

**Issue by nekromoff** [superfaktura/apiclient#23]
Deprecated: Return type of Requests_Response_Headers::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ...vendor/superfaktura/apiclient/SFAPIclient/Requests/Response/Headers.php on line 27

Deprecated: Return type of Requests_Response_Headers::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ...vendor/superfaktura/apiclient/SFAPIclient/Requests/Response/Headers.php on line 38

Deprecated: Return type of Requests_Response_Headers::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ...vendor/superfaktura/apiclient/SFAPIclient/Requests/Response/Headers.php on line 51

Deprecated: Return type of Requests_Response_Headers::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ...vendor/superfaktura/apiclient/SFAPIclient/Requests/Response/Headers.php on line 73

Deprecated: Return type of Requests_Response_Headers::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ...vendor/superfaktura/apiclient/SFAPIclient/Requests/Response/Headers.php on line 82

**Comment by adamkiss** [comment]
Chyba stále existuje

**Comment by superfaktura** [comment]
API klient si vyžaduje viacero zásadnejších úprav, ktoré sme už dlhšie zbierali. Preto sme sa rozhodli, že API klienta výraznejšie prekopeme.
Ako rýchlu náplasť sme nastavili horný limit na verziu PHP.

**Comment by erikgreasy** [comment]
Tiez som viackrat narazil na spominany problem s nekompatibilitou, ak by ste chceli tak som zatial vytvoril simple volne dostupneho klienta ako (docasnu?) nahradu: https://github.com/erikgreasy/superfaktura-client
Mozno to niekomu pomoze a usetri namahu :)
