### ISSUE TITLE
Missing createRegularFromProforma() method from version 2.x

### ISSUE THREAD

**Issue by kviktor1230** [superfaktura/apiclient#24]
I've noticed that the function createRegularFromProforma() appears to be missing from version 2.x. 
Could you please clarify if this functionality will be reintroduced in future releases, or if it has been permanently removed?

Thank you

**Comment by superfaktura** [comment]
Hi Viktor,

We can confirm that the `createRegularFromProforma()` functionality has been temporarily removed in version 2.0, but we have plans to reintroduce this functionality in our upcoming minor version release.

**Comment by superfaktura** [comment]
Hi Viktor,

We're pleased to inform you that as of our latest release, version 2.1, the `createRegularFromProforma()` functionality has been reintroduced. 

We consider this issue to be resolved, if you have any more questions or require further assistance, please don't hesitate to reach out.
