### ISSUE TITLE
English docs

### ISSUE THREAD

**Issue by vasspilka** [superfaktura/apiclient#5]
Hello, I'm building an internal application for one of your clients, we need to integrate it with your api to automate invoice related tasks. I speak Czech, however having hard time to comprehend written material, even more so in Slovak, and especially tech documents :P .
So I was wondering whether you have English documentation lying around, or if you are planning to have some before late Jan. With preference to the curl readme, or some other sort of endpoint & params specification/documentation, as we will most likely be building our own solution.
I will manage without it, but it would certainly save me from a lot of frustration.

Thank you!

**Comment by superfaktura** [comment]
Hello, first of all - I'm sorry for the delayed reply. Unfortunately, there isn't an English documentation. But in case of any troubles you can contact us on info@superfaktura.cz. We will do our best to help you with the integration.
