### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by itsZahradnik** [superfaktura/apiclient#7]
Dobrý den,
v balíku byla provedena 27. listopadu 2017 změna v souboru "superfaktura\apiclient\SFAPIclient\SFAPIclient.php" (commit: https://github.com/superfaktura/apiclient/commit/f7047cce5a2c63175f06453bc92fb77dd598bc54#diff-0a45666447e42ac6ca101e3b4a6bbb53). Jenže již nedošlo ke změně požadované verze PHP pro následující verzi balíku. PHP5.3 nepodporuje "[]" místo "array()".

**Comment by superfaktura** [comment]
Děkujeme za upozornění, už je to opravené. Omlouváme se za vzniklé potíže.
