### ISSUE TITLE
lang codes

### ISSUE THREAD

**Issue by oliverhabara** [superfaktura/apiclient#8]
Dobry den, bolo by mozne pridat moznost pouzivat aj dvojznakove kody jazykov? napriklad pre slovencinu: sk alebo madarcinu: hu ? (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Comment by superfaktura** [comment]
Dobrý deň,  momentálne používame normu 639-2 (http://www.loc.gov/standards/iso639-2/php/code_list.php), ktorá je podporovaná našim frameworkom a zmenu na inú normu momentálne neplánujeme.
